spring:
  datasource:
    url: jdbc:postgresql://postgres:GtPvzhiJJnfBZBmmKBwprNKuGPucRuDu@tramway.proxy.rlwy.net:28998/railway
    username: postgres
    password: GtPvzhiJJnfBZBmmKBwprNKuGPucRuDu
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create